[package]
name = "lunr"
version = "0.1.0"
authors = ["Oliver Nightingale <oliver.nightingale1@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
erased-serde = "0.3"
unicode-segmentation = "1.2"